
name: objc_init
version: 0.0.1
language: objc
description: Objc environment initialize
public: true
tags:
  - objc
  - init
inputs:
  - name: FLOW_VERSION
    editable: false
outputs:
script_path: ./run.sh  
  
template: |  
  
  